### ISSUE TITLE
Creación Usuarios Sistema de stock

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Modernizacion#7]
Por favor habría que dar de alta a los siguientes usuarios en el sistema de stock (JUZGADO):
- rcolombo
- mlegarda
- jmaldonado

Tengo entendido que los mismos tienen un usuario existente acá en el APR.
 
El perfil asignado debería ser solo de lectura.

Gracias.

**Comment by julianalmandos** [comment]
Los usuarios ya fueron creados con sus respectivos permisos.
